In [183]:
import pandas as pd
import requests

In [184]:
api_url = 'https://api.restcountries.com/countries/v5?limit=100'
api_headers = {"Authorization": "Bearer rc_live_1cc8d0a4bd7e41f48035b291df56ada8"}

In [185]:
response = requests.get(api_url,headers=api_headers )
raw_json = response.json()
df = pd.DataFrame(raw_json)
df.head()

                                                      data
objects  [{'names': {'alternates': ['Apsny'], 'common':...
meta     {'total': 254, 'count': 100, 'limit': 100, 'of...

In [196]:
country_list = raw_json['data']['objects']
df = pd.DataFrame(country_list)
df.head()

,names,codes,capitals,flag,region,subregion,area,assets,borders,calling_codes,...,links,memberships,number_format,parent,population,postal_code,timezones,tlds,uuid,_meta
0,"{'alternates': [], 'common': 'Singapore', 'nat...","{'alpha_2': 'SG', 'alpha_3': 'SGP', 'ccn3': '7...","[{'attributes': {'administrative': False, 'con...","{'colors': {'dominant': '#ef272b', 'palette': ...",Asia,South-Eastern Asia,"{'kilometers': 710, 'miles': 274.1}",[],[],[65],...,{'google_maps': 'https://goo.gl/maps/QbQt9Y9b5...,"{'african_union': False, 'arab_league': False,...","{'decimal_separator': '.', 'thousands_separato...","{'alpha_2': '', 'alpha_3': ''}",6110200,"{'format': '######', 'regex': '^(\d{6})$'}",[UTC+08:00],"[.sg, .新加坡, .சிங்கப்பூர்]",67c93bfb-ea02-4bab-a7d1-c8da57599f9d,{'lastUpdatedTimestamp': 1782525049}
1,"{'alternates': ['Sint Maarten (Dutch part)'], ...","{'alpha_2': 'SX', 'alpha_3': 'SXM', 'ccn3': '5...","[{'attributes': {'administrative': False, 'con...","{'colors': {'dominant': '#b41011', 'palette': ...",Americas,Caribbean,"{'kilometers': 34, 'miles': 13.1}",[],[MAF],[1],...,{'google_maps': 'https://goo.gl/maps/DjvcESy1a...,"{'african_union': False, 'arab_league': False,...","{'decimal_separator': '.', 'thousands_separato...","{'alpha_2': 'NL', 'alpha_3': 'NLD'}",58477,"{'format': '', 'regex': ''}",[UTC-04:00],[.sx],bdfd8339-d2e7-4cf7-b6af-486835e383fc,{'lastUpdatedTimestamp': 1782525046}
2,"{'alternates': [], 'common': 'Slovakia', 'nati...","{'alpha_2': 'SK', 'alpha_3': 'SVK', 'ccn3': '7...","[{'attributes': {'administrative': False, 'con...","{'colors': {'dominant': '#0054a3', 'palette': ...",Europe,Central Europe,"{'kilometers': 49037, 'miles': 18933.3}",[],"[AUT, CZE, HUN, POL, UKR]",[421],...,{'google_maps': 'https://goo.gl/maps/uNSH2wW4b...,"{'african_union': False, 'arab_league': False,...","{'decimal_separator': ',', 'thousands_separato...","{'alpha_2': '', 'alpha_3': ''}",5405368,"{'format': '### ##', 'regex': '^(\d{5})$'}",[UTC+01:00],[.sk],59b36592-7b91-4a51-877d-762655777b57,{'lastUpdatedTimestamp': 1781804766}
3,"{'alternates': [], 'common': 'Slovenia', 'nati...","{'alpha_2': 'SI', 'alpha_3': 'SVN', 'ccn3': '7...","[{'attributes': {'administrative': False, 'con...","{'colors': {'dominant': '#ff1419', 'palette': ...",Europe,Central Europe,"{'kilometers': 20273, 'miles': 7827.4}",[],"[AUT, HRV, ITA, HUN]",[386],...,{'google_maps': 'https://goo.gl/maps/7zgFmswcC...,"{'african_union': False, 'arab_league': False,...","{'decimal_separator': ',', 'thousands_separato...","{'alpha_2': '', 'alpha_3': ''}",2135107,"{'format': 'SI- ####', 'regex': '^(?:SI)*(\d{4...",[UTC+01:00],[.si],b9288a1b-0592-4af5-909d-071665f3859e,{'lastUpdatedTimestamp': 1782543051}
4,"{'alternates': ['The Solomons'], 'common': 'So...","{'alpha_2': 'SB', 'alpha_3': 'SLB', 'ccn3': '0...","[{'attributes': {'administrative': False, 'con...","{'colors': {'dominant': '#1a5c34', 'palette': ...",Oceania,Melanesia,"{'kilometers': 28896, 'miles': 11156.8}",[],[],[677],...,{'google_maps': 'https://goo.gl/maps/JbPkx86Yw...,"{'african_union': False, 'arab_league': False,...","{'decimal_separator': '.', 'thousands_separato...","{'alpha_2': '', 'alpha_3': ''}",828857,"{'format': '', 'regex': ''}",[UTC+11:00],[.sb],e5ab8074-2bab-4a02-b68d-cccd1ed7ffa0,{'lastUpdatedTimestamp': 1782532587}

In [187]:
df.shape

(100, 32)

In [188]:
all_countries = []
for offset in range(0, 300, 100):
    api_url = f"https://api.restcountries.com/countries/v5?limit=100&offset={offset}"
    response = requests.get(api_url, headers=api_headers)
    raw_json = response.json()
    if 'data' not in raw_json or len(raw_json['data']['objects']) == 0:
        break
        
    all_countries.extend(raw_json['data']['objects'])

In [189]:
df = pd.DataFrame(all_countries)
df.shape

(254, 32)

In [190]:
# Used to Helped to fetch capital easily now useless
df['capitals'][0][0]['name']
df['capitals'].apply(type).value_counts()
#df['capitals'].apply(len).value_counts()

capitals
<class 'list'>    254
Name: count, dtype: int64

In [191]:
df.iloc[0]
# DONE - Name, Captial,Region,Sub-region,Area,Borders,calling_codes,continents,currencies,govt_type,landlocked,language,

names              {'alternates': ['Apsny'], 'common': 'Abkhazia'...
codes              {'alpha_2': '', 'alpha_3': '', 'ccn3': '', 'ci...
capitals           [{'attributes': {'administrative': False, 'con...
flag               {'colors': {'dominant': '', 'palette': [], 'pr...
region                                                          Asia
subregion                                               Western Asia
area                           {'kilometers': 8665, 'miles': 3345.6}
assets                                                            []
borders                                                   [GEO, RUS]
calling_codes                                                    [7]
cars                          {'driving_side': 'right', 'signs': []}
classification     {'dependency': False, 'dependency_type': '', '...
continents                                                    [Asia]
coordinates                                   {'lat': 43, 'lng': 41}
currencies         [{'code': 'RUB', 'name': 'Russian ruble', 'sym...
date               {'academic_year_start': {'day': 1, 'month': 9}...
demonyms           {'eng': {'f': 'Abkhaz', 'm': 'Abkhaz'}, 'fra':...
economy                                     {'gini_coefficient': {}}
government_type                        Unitary presidential republic
landlocked                                                     False
languages          [{'bcp47': 'ab', 'iso639_1': 'ab', 'iso639_2b'...
leaders            [{'message': 'data.leaders is only available o...
links              {'google_maps': '', 'official': 'http://presid...
memberships        {'african_union': False, 'arab_league': False,...
number_format      {'decimal_separator': ',', 'thousands_separato...
parent                           {'alpha_2': 'GE', 'alpha_3': 'GEO'}
population                                                    244000
postal_code                              {'format': '', 'regex': ''}
timezones                                                [UTC+03:00]
tlds                                                              []
uuid                            0e1bae13-c4c6-40d7-955f-f2c6062381cc
_meta                           {'lastUpdatedTimestamp': 1782525046}
Name: 0, dtype: object

In [192]:
df['Country'] = df['names'].apply(lambda x: x['common'])
df['Capital'] = df['capitals'].apply(lambda x: x[0]['name'] if len(x) > 0 else None)
df['Capital-Lat'] = df['capitals'].apply(lambda x: x[0]['coordinates']['lat'] if len(x) > 0 else None)
df['Capital-Lng'] = df['capitals'].apply(lambda x: x[0]['coordinates']['lng'] if len(x) > 0 else None)
df['Population'] = df['population']
df['Region'] = df['region']
df['Sub-Region'] = df['subregion']
df['Timezone'] = df['timezones']
df['Area(km)'] = df['area'].apply(lambda x: x['kilometers'])
df['Border Nation'] = df['borders']
df['Government'] = df['government_type']
df['Call - Codes'] = df['calling_codes'].apply(lambda x: x[0] if x else None)
df['Continent'] = df['continents'].apply(lambda x: x[0] if x else None)
df['Currency_Code'] = df['currencies'].apply(lambda x: x[0]['code'] if x else None)
df['Currency_Name'] = df['currencies'].apply(lambda x: x[0]['name'] if x else None)
df['Currency_Symbol'] = df['currencies'].apply(lambda x: x[0]['symbol'] if x else None)
df['Languages'] = df['languages'].apply(lambda x: ', '.join(lang['name'] for lang in x) if x else None)
df['Driving_Side'] = df['cars'].apply(lambda x: x['driving_side'] if x else None)


clean_df = df[[
    'Country',
    'Capital',
    'Capital-Lat',
    'Capital-Lng',
    'Population',
    'Area(km)',
    'Continent',
    'Region',
    'Sub-Region',
    'Languages',
    'Driving_Side',
    'Government',
    'Currency_Code',
    'Currency_Name',
    'Currency_Symbol',
    'Call - Codes',
    'Timezone',
    'Border Nation'
]]

clean_df = clean_df.set_index('Country')
clean_df

,Capital,Capital-Lat,Capital-Lng,Population,Area(km),Continent,Region,Sub-Region,Languages,Driving_Side,Government,Currency_Code,Currency_Name,Currency_Symbol,Call - Codes,Timezone,Border Nation
Country,,,,,,,,,,,,,,,,,
Abkhazia,Sukhumi,43.0033,41.0153,244000,8665.0,Asia,Asia,Western Asia,"Abkhaz, Russian",right,Unitary presidential republic,RUB,Russian ruble,₽,7,[UTC+03:00],"[GEO, RUS]"
Afghanistan,Kabul,34.5200,69.1800,35000000,652230.0,Asia,Asia,Southern Asia,"Dari, Pashto, Turkmen",right,Unitary totalitarian theocratic Islamic emirate,AFN,Afghan afghani,؋,93,[UTC+04:30],"[IRN, PAK, TKM, UZB, TJK, CHN]"
Albania,Tirana,41.3200,19.8200,2402113,28748.0,Europe,Europe,Southeast Europe,Albanian,right,Unitary parliamentary republic,ALL,Albanian lek,L,355,[UTC+01:00],"[MNE, GRC, MKD, UNK]"
Algeria,Algiers,36.7500,3.0500,47400000,2381741.0,Africa,Africa,Northern Africa,Arabic,right,Unitary semi-presidential republic,DZD,Algerian dinar,د.ج,213,[UTC+01:00],"[TUN, LBY, NER, ESH, MRT, MLI, MAR]"
American Samoa,Pago Pago,-14.2700,-170.7000,43268,199.0,Oceania,Oceania,Polynesia,"English, Samoan",right,Devolved presidential constitutional dependency,USD,United States dollar,$,1,[UTC-11:00],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,El Aaiún,27.1253,-13.1625,510713,266000.0,Africa,Africa,Northern Africa,"Hassaniya Arabic, Spanish",right,,DZD,Algerian dinar,دج,212,[UTC+00:00],"[DZA, MRT, MAR]"
Yemen,Sana'a,15.3700,44.1900,32684503,527968.0,Asia,Asia,Western Asia,Arabic,right,Unitary semi-presidential republic under a pro...,YER,Yemeni rial,﷼,967,[UTC+03:00],"[OMN, SAU]"
Zambia,Lusaka,-15.4200,28.2800,20216029,752612.0,Africa,Africa,Eastern Africa,English,left,Unitary presidential republic,ZMW,Zambian kwacha,ZK,260,[UTC+02:00],"[AGO, BWA, COD, MWI, MOZ, NAM, TZA, ZWE]"
Zimbabwe,Harare,-17.8200,31.0300,17166852,390757.0,Africa,Africa,Southern Africa,"Barwe, English, Kalanga, Khoisan languages, Nd...",left,Unitary presidential republic,ZWL,Zimbabwean dollar,$,263,[UTC+02:00],"[BWA, MOZ, ZAF, ZMB]"
Åland Islands,Mariehamn,60.1200,19.9000,30654,1580.0,Europe,Europe,Northern Europe,Swedish,right,Devolved parliamentary autonomous region,EUR,Euro,€,358,[UTC+02:00],[]

In [194]:
clean_df.to_csv('countries-info.csv')